datasource:
  url: jdbc:mysql://localhost:3306/COREBANKING
  username: root
  password: s3cret
  driverClassName: com.mysql.cj.jdbc.Driver
  maxPoolSize: 50
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  hibernate:
    hbm2ddl.method: validate
    show_sql: false
    format_sql: false
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    timeout: 2000
